config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  get "pokemons", to: "pokemons#index"

  get "pokemons/search", to: "pokemons#search"

  resources :moves, only: [:index] do

  end

  resources :pokemons, only: [:index, :show] do
  end

  # Create game session
  resources :games, only: [:new, :create, :show] do
    resources :teams, only: [:new, :create, :show, :edit] do
      resources :selected_pokemons
    end
      resources :battles do
        resources :actions, only: [:create] do
      end
    end
  end


end


# Test commment

app/views/shared/_navbar.html.erb
<nav>
  <% if user_signed_in? %>
    <%= link_to "Log out",
                destroy_user_session_path,
                data: { turbo_method: :delete } %>
  <% end %>
</nav>

app/views/shared/_teamdisplay.html.erb
<h3 style="text-align: center;"> <%= link_to "My Team", game_team_path(@game, @team) %> </h3>

<div class="myteam">

<table>
<% if selected_pokemon %>
<% selected_pokemon.each do |selected| %>
  <% if selected[:team_id] == team.id%>
  <tr>
    <td> <%= selected[:team_id] %> </td>
    <td> <%= selected[:pokemon_id] %> </td>
    <td> <%= selected.pokemon[:name] %> </td>
    <td> <img src="<%= selected.pokemon[:picture] %>"> </td>
    <td> <% if selected[:move1] != "" %> <%= Move.find(selected[:move1]).name %> <% end %> </td>
     <td> <% if selected[:move2] != "" %> <%= Move.find(selected[:move2]).name %> <% end %> </td>
     <td> <% if selected[:move3] != "" %> <%= Move.find(selected[:move3]).name %> <% end %> </td>
     <td> <% if selected[:move4] != "" %> <%= Move.find(selected[:move4]).name %> <% end %> </td>
     <td> <button> <%= link_to "Remove", game_team_selected_pokemon_path(id: selected.id, team_id: selected.team_id),
        data: { turbo_method: :delete }, turbo_confirm: "Are you sure you want to remove this Pokemon?", status: :see_other %> </button>

      </button> </td>
     <td> <button> <%= link_to "Edit", edit_game_team_selected_pokemon_path(@game, @team, selected) %> </button> </td>
  </tr>
  <% end %>
<%end%>
<% end %>
</table>
</div>